//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITGlobalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyLeaveType
    {
        public int ID { get; set; }
        public int ID_Leave_Type { get; set; }
        public int ID_Employee { get; set; }
        public int LeavePeriod { get; set; }
        public int Entitlement { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual LeaveType LeaveType { get; set; }
    }
}
