//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITGlobalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Debts()
        {
            this.PaymentHistory = new HashSet<PaymentHistory>();
        }
    
        public int ID { get; set; }
        public int ID_Project { get; set; }
        public string Stage { get; set; }
        public decimal Price { get; set; }
        public System.DateTime Date { get; set; }
        public bool State { get; set; }
        public Nullable<bool> Send_Email_State { get; set; }
    
        public virtual Projects Projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentHistory> PaymentHistory { get; set; }
    }
}
