//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITGlobalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.Comment = new HashSet<Comment>();
            this.Histories = new HashSet<Histories>();
            this.Notification = new HashSet<Notification>();
            this.Payroll = new HashSet<Payroll>();
            this.Tasks = new HashSet<Tasks>();
            this.Teams = new HashSet<Teams>();
        }
    
        public int ID { get; set; }
        public int ID_Position { get; set; }
        public string IdentityCard { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Sex { get; set; }
        public string Address { get; set; }
        public Nullable<int> NumberOfDependants { get; set; }
        public decimal Wage { get; set; }
        public string BankName { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankAccountHolderName { get; set; }
        public bool Lock { get; set; }
        public Nullable<System.DateTime> AccessHistory { get; set; }
        public System.DateTime WorkDate { get; set; }
        public string Avatar { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> Code_Time { get; set; }
        public string Password { get; set; }
        public string Username { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual Position Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Histories> Histories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payroll> Payroll { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tasks> Tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teams> Teams { get; set; }
    }
}
