//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITGlobalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguagesSkills
    {
        public int ID { get; set; }
        public int ID_Employee { get; set; }
        public string Name { get; set; }
        public string Writing { get; set; }
        public string Speaking { get; set; }
        public string Reading { get; set; }
        public string listening { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
