//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITGlobalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerOfProject
    {
        public int ID { get; set; }
        public int ID_Partners { get; set; }
        public int ID_Project { get; set; }
    
        public virtual Partners Partners { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
