//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITGlobalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payroll()
        {
            this.Histories = new HashSet<Histories>();
            this.SubsidiesApply = new HashSet<SubsidiesApply>();
        }
    
        public int ID { get; set; }
        public int ID_PayrollCategory { get; set; }
        public int ID_Employee { get; set; }
        public decimal Salary { get; set; }
        public decimal SocialInsurance { get; set; }
        public decimal HealthInsurance { get; set; }
        public decimal UnemploymentInsurance { get; set; }
        public decimal InsuranceCeiling { get; set; }
        public decimal TotalPriceInsurance { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> TaxDeductions { get; set; }
        public Nullable<int> NumberOfDependents { get; set; }
        public Nullable<decimal> DependencyDeduction { get; set; }
        public Nullable<decimal> FamilyAllowances { get; set; }
        public Nullable<decimal> TaxableSalary { get; set; }
        public Nullable<decimal> TotalPriceTax { get; set; }
        public Nullable<decimal> NumberDaysLeave { get; set; }
        public Nullable<decimal> PriceForOneDayOff { get; set; }
        public Nullable<decimal> Total_Price { get; set; }
        public Nullable<bool> State { get; set; }
        public Nullable<decimal> SalaryTaxable { get; set; }
        public Nullable<decimal> SalaryInsurance { get; set; }
        public Nullable<decimal> MissingAmount { get; set; }
        public Nullable<decimal> TotalAllowance { get; set; }
    
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Histories> Histories { get; set; }
        public virtual PayrollCategory PayrollCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubsidiesApply> SubsidiesApply { get; set; }
    }
}
