//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITGlobalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recruitment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recruitment()
        {
            this.SkillOfRecruitment = new HashSet<SkillOfRecruitment>();
        }
    
        public int ID { get; set; }
        public int ID_Position { get; set; }
        public string Title { get; set; }
        public int Amount { get; set; }
        public string Form { get; set; }
        public string Sex { get; set; }
        public string Experience { get; set; }
        public decimal MinimumWage { get; set; }
        public string JobDescription { get; set; }
        public string CandidateRequirement { get; set; }
        public string CandidateBenefits { get; set; }
        public bool Status { get; set; }
        public System.DateTime DateCreateOrPosted { get; set; }
        public long Views { get; set; }
        public decimal MaximumWage { get; set; }
        public System.DateTime CVSubmissionDeadline { get; set; }
    
        public virtual Position Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkillOfRecruitment> SkillOfRecruitment { get; set; }
    }
}
